packages/moxie-agent-lib/src/index.ts, packages/plugin-moxie-limit-order/src/actions/limitOrderAction.ts, packages/plugin-moxie-token-transfer/src/actions/transferAction.ts
- [] Low
- [] Medium
- [] High
=> added fix for deploy issue

packages/moxie-agent-lib/src/services/moxieUserService.ts, packages/moxie-agent-lib/src/services/types.ts, packages/plugin-moxie-whale-hunter/src/actions/topTokenHoldersAction.ts
- [] Low
- [] Medium
- [] High
=> commit to add minimal user response

packages/plugin-moxie-swap/src/utils/subgraph.ts, packages/plugin-moxie-token-transfer/src/actions/transferAction.ts, packages/plugin-moxie-token-transfer/src/utils/subgraph.ts, packages/plugin-moxie-whale-hunter/src/protocolSubgraph.ts
- [] Low
- [] Medium
- [] High
Added retry to subgraph api calls
=> fix: added retry to subgraph calls

packages/plugin-moxie-limit-order/src/actions/limitOrderAction.ts
Check agent wallet for alternate tokens on insufficient balance
When a user has insufficient balance of the selected token, scan agent wallet for other tokens with sufficient balance and suggest the top 3 alternatives. Exclude the buyToken from suggestions even if it has adequate balance.
- [] Medium
- [] High
Exclude buyToken from alternative token suggestions for insufficient balance check
=> fix: exclude buyToken from alternative token suggestions for insufficient balance check

packages/plugin-moxie-limit-order/src/actions/limitOrderAction.ts
- [] Low
- [] Medium
- [] High
=> fix: issue with limit order plugin

registry/src/skills.json
- [] Medium
- [] High
Fixes incorrect starter question user and token tagging in skills.json
=> fix: starter question values for agent

packages/plugin-moxie-limit-order/src/actions/limitOrderAction.ts
Reverts moxie-protocol/moxie-agent-skills#25
=> Revert "fix: exclude buyToken from alternative token suggestions for insufficient balance check"

registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> added missing loader

packages/plugin-moxie-balance/src/actions/getMoxieFanTokenPortfolio/index.ts, packages/plugin-moxie-balance/src/actions/getMoxiePortfolio/index.ts
- [] Low
- [] Medium
- [] High
=>  Initialing moxieUserInfoMultiple in balance plugin

packages/moxie-agent-lib/src/index.ts, packages/moxie-agent-lib/src/services/MoxieAgentDBAdapter.ts, packages/moxie-agent-lib/src/services/zapperService.ts
- [] Low
- [] Medium
- [] High
=> added upsertFreeTrialBalance

packages/moxie-agent-lib/src/services/moxieUserService.ts
- [] Low
- [] Medium
- [] High
=> adding retry for the API

packages/moxie-agent-lib/src/services/moxieUserService.ts, packages/plugin-moxie-balance/src/actions/getMoxieFanTokenPortfolio/index.ts, packages/plugin-moxie-balance/src/actions/getMoxiePortfolio/index.ts, packages/plugin-moxie-social-alpha/src/actions/swapSummaryAction.ts
- [] Low
- [] Medium
- [] High
=> throwing error in case retry fails

packages/plugin-moxie-limit-order/src/actions/limitOrderAction.ts, packages/plugin-moxie-limit-order/src/constants/constants.ts, packages/plugin-moxie-limit-order/src/service/cowLimitOrder.ts, packages/plugin-moxie-limit-order/src/utils/0xApis.ts, packages/plugin-moxie-limit-order/src/utils/checkAndApproveTransaction.ts, packages/plugin-moxie-social-alpha/src/constants/constants.ts, packages/plugin-moxie-social-alpha/src/services/farcasterService.ts, packages/plugin-moxie-swap/src/constants/constants.ts, packages/plugin-moxie-swap/src/utils/0xApis.ts, packages/plugin-moxie-swap/src/utils/checkAndApproveTransaction.ts, packages/plugin-moxie-swap/src/utils/moxieBondingCurve.ts, packages/plugin-moxie-swap/src/utils/subgraph.ts, packages/plugin-moxie-token-social-sentiment/src/constants/constants.ts, packages/plugin-moxie-token-social-sentiment/src/services/neynarService.ts, packages/plugin-moxie-token-transfer/src/actions/transferAction.ts, packages/plugin-moxie-token-transfer/src/constants/constants.ts, packages/plugin-moxie-token-transfer/src/utils/0xApis.ts, packages/plugin-moxie-token-transfer/src/utils/subgraph.ts, packages/plugin-moxie-whale-hunter/src/constants/constants.ts, packages/plugin-moxie-whale-hunter/src/protocolSubgraph.ts
```
NEYNAR_API_KEY
PROTOCOL_SUBGRAPH_URL
ZERO_EX_API_KEY
```
- [] Low
- [] Medium
- [] High
=> added mock response for missing

packages/plugin-moxie-balance/src/actions/getMoxiePortfolio/index.ts
- [] Low
- [] Medium
- [] High
=> added missing condition

packages/moxie-agent-lib/src/services/moxieUserService.ts
- [] Low
- [] Medium
- [] High
=> Get user is now private

packages/client-moxie/src/constants/constants.ts, packages/moxie-agent-lib/src/services/constants.ts, packages/moxie-agent-lib/src/services/types.ts
- Fix mock moxie user data to fit prod data for local development
- [] Low
- [] Medium
- [] High
=> modify mock user data structure

README.md
Updating skills.json documentation in README
- [] Low
- [] Medium
- [] High
=> updating skills.json docs

registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> Minor fix on skill coin

registry/src/skills.json
fixed image, lowercase & added freemium
- [] Medium
- [] High
fixed image, lowercase & added freemium
=> DegenFans AlfafFrens

packages/moxie-agent-lib/src/services/MoxieAgentDBAdapter.ts
- [] Low
- [] Medium
- [] High
=> added toLowercase on address query

packages/moxie-agent-lib/src/services/moxieUserService.ts
- [] Low
- [] Medium
- [] High
=> removed unwanted functions

registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> removed premium

packages/plugin-moxie-limit-order/src/actions/limitOrderAction.ts
- [] Low
- [] Medium
- [] High
=> updating url to point to internal

registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> remove trailing comma

registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> fix merge conflict issue from betswirl

packages/moxie-agent-lib/src/services/tokenDetails.ts, packages/plugin-moxie-social-alpha/src/actions/swapSummaryAction.ts, packages/plugin-moxie-social-alpha/src/templates.ts, packages/plugin-moxie-social-alpha/src/utils.ts
- [] Low
- [] Medium
- [] High
=> added timeFilter in trending tokens

packages/plugin-moxie-swap/src/utils/codexApis.ts
- [] Low
- [] Medium
- [] High
=> fix: remove network id from token address

packages/moxie-agent-lib/src/services/tokenDetails.ts
- [] Low
- [] Medium
- [] High
=> token details previous fields fetching

packages/moxie-agent-lib/src/services/tokenDetails.ts
- [] Low
- [] Medium
- [] High
=> return tokens

packages/plugin-moxie-limit-order/src/utils/cowUsdPrice.ts
- [] Low
- [] Medium
- [] High
=> fix: use weth for usdprice from cowswap

packages/plugin-moxie-balance/src/actions/getMoxiePortfolio/template.ts
- [] Low
- [] Medium
- [] High
=> portfolio changes

packages/plugin-moxie-swap/src/actions/tokenSwapAction.ts, packages/plugin-moxie-swap/src/utils/0xApis.ts
- [] Low
- [] Medium
- [] High
=> feat: swap fee changes

packages/plugin-moxie-token-transfer/src/templates/template.ts
- [] Low
- [] Medium
- [] High
=> fix: incorrect processing of $ value

packages/plugin-moxie-limit-order/src/utils/0xApis.ts, packages/plugin-moxie-swap/src/utils/0xApis.ts
- [] Low
- [] Medium
- [] High
=> fix: add retry to 0x apis

packages/moxie-agent-lib/src/services/MoxieAgentDBAdapter.ts, registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> added orderIndex

registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> Make farcaster cast skill as default skill

packages/plugin-moxie-swap/src/templates/tokenSwapTemplate.ts
- [] Low
- [] Medium
- [] High
=> removing creator coins from swap template

packages/plugin-moxie-swap/src/actions/tokenSwapAction.ts
- [] Low
- [] Medium
- [] High
=> fix: handle token lower case during decoding

packages/plugin-bootstrap/src/actions/agentCapabilities.ts, packages/plugin-bootstrap/src/index.ts
- [] Low
- [] Medium
- [] High
=> senpi agent action - agent capabilities

packages/plugin-moxie-limit-order/src/constants.ts, packages/plugin-moxie-limit-order/src/utils/0xApis.ts, packages/plugin-moxie-swap/src/utils/0xApis.ts, packages/plugin-moxie-swap/src/utils/constants.ts
- [] Low
- [] Medium
- [] High
Setup dynamic slippage for 0x swap quote api
=> slippage changes

packages/plugin-moxie-autonomous-trading/src/utils/utility.ts, packages/plugin-moxie-groups/src/templates.ts, pnpm-lock.yaml
- [] Low
- [] Medium
- [] High
=> senpi group plugin  hallucination fix

registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> update custom loaders for tutorial skills

packages/plugin-moxie-balance/src/actions/getMoxiePortfolio/index.ts
- [] Low
- [] Medium
- [] High
=> added missing API calls intead of tokenGate

packages/plugin-moxie-groups/src/templates.ts
- [] Low
- [] Medium
- [] High
=> group template change

packages/plugin-moxie-balance/src/actions/getMoxiePortfolio/index.ts
- [] Low
- [] Medium
- [] High
=> aded logs na catch hadling

packages/plugin-moxie-groups/src/templates.ts
- [] Low
- [] Medium
- [] High
=> group action type selection

agent/src/index.ts, packages/plugin-senpi-tutorial/src/actions/learnSenpiAction.ts, packages/plugin-senpi-tutorial/src/actions/tutorialAction.ts, packages/plugin-senpi-tutorial/src/index.ts, packages/plugin-senpi-tutorial/src/templates.ts, packages/plugin-senpi-tutorial/src/utils/format.ts, packages/plugin-senpi-tutorial/tsup.config.ts, pnpm-lock.yaml
We want to add Youtube videos for each reply from the Tutorial Skill. These changes are the backend (agent-side) changes to support the youtube embedding
-  [] Updates (new versions of included code)
=> Add support for youtube embed on tutorial skills

packages/moxie-agent-lib/src/services/MoxieAgentDBAdapter.ts
- [] Low
- [] Medium
- [] High
=> updating limit order multiple

packages/plugin-profit-loss/src/actions/pnlAction.ts, packages/plugin-profit-loss/src/service/pnlService.ts
- Changed modelClass in PnL action from SMALL to MEDIUM and added modelConfigOptions for improved API interaction.
- Enhanced logging in pnlService to include the current Node environment, aiding in debugging and performance monitoring.
=> Update PnL action and service to enhance model configuration and logging

packages/plugin-moxie-autonomous-trading/src/actions/index.ts, packages/plugin-moxie-autonomous-trading/src/templates.ts, packages/plugin-moxie-autonomous-trading/src/utils/utility.ts
- [] Low
- [] Medium
- [] High
=> mcap and age filter changes

packages/plugin-moxie-autonomous-trading/src/actions/index.ts
- [] Low
- [] Medium
- [] High
=> additional params exported by model

pnpm-lock.yaml
- [] Low
- [] Medium
- [] High
=> pnpm build failing

packages/plugin-profit-loss/src/actions/pnlAction.ts
- [] Low
- [] Medium
- [] High
=> updating error message

packages/plugin-moxie-autonomous-trading/src/actions/index.ts, packages/plugin-moxie-autonomous-trading/src/templates.ts, packages/plugin-moxie-autonomous-trading/src/utils/utility.ts
- [] Low
- [] Medium
- [] High
=> stop loss params

packages/plugin-moxie-whale-hunter/src/templates.ts
- Changed the section title to clarify that the data pertains to the last 24 hours.
- Removed redundant note about time limitations, as it is now implied in the updated title.
- [] Low
- [] Medium
- [] High
=> Fix Top Traders Hallucination

packages/plugin-profit-loss/src/template.ts
…y required fields in response. Updated query types for better organization and consistency.
- [] Low
- [] Medium
- [] High
=> Remove Accidental Merge Conflicts

packages/plugin-moxie-limit-order/src/templates/limitOrderPrompt.ts
- [] Low
- [] Medium
- [] High
=> fix: limit order prompt enhancement to detect order type buy/sell

packages/plugin-senpi-tutorial/src/templates.ts
- Enable tutorial skill to recommend "Autonomous Trade" youtube tutorial when asked how to set up multi-rule trade orders
- Add **NEW** stop loss tutorial from Alex
=> Improve tutorial skill

packages/plugin-senpi-tutorial/src/templates.ts
Introduced a new tutorial for the Senpi Scam Shield feature, aimed at helping users protect themselves from scams and assisting those who have difficulty using the feature. Updated the templates to include the relevant link for the tutorial.
- [] Low
- [] Medium
- [] High
=> Add Senpi Scam Shield Tutorial to templates

packages/plugin-profit-loss/src/template.ts
…rame when none is mentioned
- [] Low
- [] Medium
- [] High
=> Update PnL response guidelines to specify "lifetime" as default timeframe

packages/plugin-senpi-stop-loss/src/actions/index.ts
- [] Low
- [] Medium
- [] High
=> messaging change

registry/src/skills.json
- [] Low
- [] Medium
- [] High
=> Minor update on Social Alpha metadata in skills.json after trending token v1 action deprecated

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts
- [] Low
- [] Medium
- [] High
=> adding cta

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts, packages/plugin-senpi-orders/src/types.ts
- [] Low
- [] Medium
- [] High
=> Stop loss agent changes

packages/plugin-senpi-orders/src/utils/common.ts
- [] Low
- [] Medium
- [] High
=> buy amount usd

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts
- [] Low
- [] Medium
- [] High
=> stop response changes

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts
- [] Low
- [] Medium
- [] High
=> limit order

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts
- [] Low
- [] Medium
- [] High
=> buy price changes

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts, packages/plugin-senpi-orders/src/templates/senpiOrdersTemplate.ts
- [] Low
- [] Medium
- [] High
=> stop loss changes

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts
- [] Low
- [] Medium
- [] High
=> formatting changes

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts
- [] Low
- [] Medium
- [] High
=> senpi prompt enhancement

packages/plugin-senpi-orders/src/actions/senpiOrdersAction.ts
- [] Low
- [] Medium
- [] High
=> limit order response fix:

packages/plugin-senpi-orders/src/templates/senpiOrdersTemplate.ts
- [] Low
- [] Medium
- [] High
=> delete the order

packages/client-moxie/src/moxieApis.ts, packages/moxie-agent-lib/src/services/zapperService.ts, packages/plugin-wallet-duster/src/actions/dustWalletAction.ts, packages/plugin-wallet-duster/src/constants/constants.ts, packages/plugin-wallet-duster/src/types.ts, packages/plugin-wallet-duster/src/utils/swap.ts, pnpm-lock.yaml
…ieApis and zapperService to include token decimals; add manual order creation functionality in wallet-duster with improved error handling and logging.
- [] Low
- [] Medium
- [] High
=> Replace swap in wallet duster with `createManualOrders` API

packages/moxie-agent-lib/src/services/moxieUserService.ts, packages/plugin-wallet-duster/src/utils/swap.ts
- [] Low
- [] Medium
- [] High
=> added Origin Header for public APIs

packages/plugin-moxie-autonomous-trading/src/actions/index.ts
- [] Low
- [] Medium
- [] High
=> token age fix

packages/plugin-moxie-autonomous-trading/src/actions/index.ts
- [] Low
- [] Medium
- [] High
=> enhancements

packages/plugin-moxie-autonomous-trading/src/actions/index.ts, packages/plugin-moxie-autonomous-trading/src/templates.ts
- [] Low
- [] Medium
- [] High
=> Automations prompt fix
